#!/bin/sh

wp="$(pwd)"
filepath=$(cd "$(dirname "$0")"; pwd)
cd $filepath
java -classpath ".:/usr/lib/jvm/java-1.6.0-openjdk.x86_64/lib/tools.jar:./lib/log4j-1.2.17.jar:./lib:./lib/mongo-java-driver-2.12.1.jar:./lib/commons-cli-1.1.jar:./lib/commons-io-1.4.jar:./lib/jodconverter-core-3.0-beta-4.jar:./lib/json-20090211.jar:./lib/juh-3.2.1.jar:./lib/jurt-3.2.1.jar:./lib/ridl-3.2.1.jar:./lib/unoil-3.2.1.jar" MainServer &
cd $wp;
